version: '3'
services:
  chirpstack-hpr:
    build: .
    image: chirpstack-hpr:latest
    container_name: chirpstack-hpr
    restart: unless-stopped
    volumes:
      - './app:/app'
      - '${HELIUM_CLI_PATH}:/usr/bin/hpr'
      - '${HELIUM_KEYPAIR_PATH}:/app/delegate_key.bin:ro'
    environment:
      - HELIUM_CONFIG_HOST=${HELIUM_CONFIG_HOST}
      - HELIUM_KEYPAIR_BIN=/app/delegate_key.bin
      - HELIUM_NET_ID=${HELIUM_NET_ID}
      - HELIUM_OUI=${HELIUM_OUI}
      - HELIUM_MAX_COPIES=${HELIUM_MAX_COPIES}
      - SERVER_HOST=${SERVER_HOST}
      - SERVER_IP=${SERVER_IP}
      - ROUTE_ID=${ROUTE_ID}
      - CHIRPSTACK_SERVER=${CHIRPSTACK_SERVER}
      - CHIRPSTACK_APIKEY=${CHIRPSTACK_APIKEY}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASS=${POSTGRES_PASS}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_DB=${POSTGRES_DB}
      - REDIS_HOST=${REDIS_HOST}
    command: bash -c 'cd /app && python app.py'

networks:
  default:
    name: core-infra
    external: true
